git:
  merging:
    args: "--no-ff"
  paging:
    externalDiffCommand: difft --color=always 
    # externalDiffCommand: difft --color=always --display=inline
services:
  'gitlab.ukbonn.de': 'gitlab:gitlab.ukbonn.de'
